export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const FETCH_ALL_MOVIES_SUCCESS = 'FETCH_ALL_MOVIES_SUCCESS';
export const FETCH_ALL_MOVIES_FAILED = 'FETCH_ALL_MOVIES_FAILED';

export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
