export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';

export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const FETCH_ALL_MOVIES_SUCCESS = 'FETCH_ALL_MOVIES_SUCCESS';
export const FETCH_ALL_MOVIES_FAILED = 'FETCH_ALL_MOVIES_FAILED';

export const DELETE_MOVIE = 'DELETE_MOVIE';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILED = 'DELETE_MOVIE_FAILED';

export const ADD_MOVIE = 'ADD_MOVIE';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILED = 'ADD_MOVIE_FAILED';

export const ADD_MOVIES_FROM_FILE_SUCCESS = 'ADD_MOVIES_FROM_FILE_SUCCESS';

export const SET_FILTER_PROPERTY = 'SET_SEARCH_PROPERTY';

export const SET_SORTING = 'SET_SORTING';

export const SEND_FILE = 'SEND_FILE';